# -*- coding: utf-8 -*-
"""Spam-Ham Classifier

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QeE9FFEWgdnBjtkAH1AZAT8Ehriko-JJ

***LIBRARIES REQUIRED***
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Model
from keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding
from keras.optimizers import RMSprop
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping
# %matplotlib inline

"""***LOAD DATA INTO DATAFRAME***

"""

df = pd.read_csv('/content/spam_or_not_spam.csv',delimiter=',',encoding='latin-1')
df.head()

df.shape

X = df.email
Y = df.label

X=X.apply(lambda x:str(x))

X.shape

"""***SPLITTING DATA INTO TRAIN AND TEST***"""

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.15)

X_train.shape

X_test.shape

"""***PREPROCESSING DATA***"""

max_words = 1000
max_len = 150
tok = Tokenizer(num_words=max_words)
tok.fit_on_texts(X_train)
sequences = tok.texts_to_sequences(X_train)
sequences_matrix = sequence.pad_sequences(sequences,maxlen=max_len)

print(sequences_matrix)

"""***RNN STRUCTURE***"""

def RNN():
    inputs = Input(name='inputs',shape=[max_len])
    layer = Embedding(max_words,50,input_length=max_len)(inputs)
    layer = LSTM(64)(layer)
    layer = Dense(256)(layer)
    layer = Activation('relu')(layer)
    layer = Dropout(0.5)(layer)
    layer = Dense(1)(layer)
    layer = Activation('sigmoid')(layer)
    model = Model(inputs=inputs,outputs=layer)
    return model

model = RNN()
model.summary()
model.compile(loss='binary_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

model.fit(sequences_matrix,Y_train,batch_size=128,epochs=10,
          validation_split=0.2,callbacks=[EarlyStopping(monitor='val_loss',min_delta=0.0001)])

test_sequences = tok.texts_to_sequences(X_test)
test_sequences_matrix = sequence.pad_sequences(test_sequences,maxlen=max_len)

accr = model.evaluate(test_sequences_matrix,Y_test)

print('Test set\n  Loss: {:0.3f}\n  Accuracy: {:0.3f}'.format(accr[0],accr[1]))